# Generated by Django 5.0.4 on 2024-05-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='contact_name',
        ),
    ]
