# Generated by Django 5.0.4 on 2024-05-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productinstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='order',
        ),
    ]
