# Generated by Django 5.0.4 on 2024-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_client_user_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
    ]
