# Generated by Django 5.0.4 on 2024-05-19 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_promocode_alter_cart_total_price_orderitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='expiration_date',
            field=models.DateField(default=datetime.date(2024, 5, 19)),
        ),
    ]
