# Generated by Django 5.0.4 on 2024-05-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_promocode_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='expiration_date',
        ),
    ]
