# Generated by Django 5.0.4 on 2024-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_promocode_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(null=True, upload_to='employee_photos/'),
        ),
    ]
