# Generated by Django 5.0.4 on 2024-05-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_client_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(default='Minsk', max_length=100),
        ),
    ]
