# Generated by Django 5.0.4 on 2024-05-19 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 21, 5, 9, 939685)),
        ),
    ]
