# Generated by Django 5.0.4 on 2024-09-23 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_article_content_alter_article_publication_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='banner1',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='banner2',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 15, 39, 25, 853354)),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(upload_to='company_info'),
        ),
    ]
