# Generated by Django 5.0.4 on 2024-09-23 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_companyinfo_banner1_companyinfo_banner2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 15, 59, 51, 900950)),
        ),
    ]
