# Generated by Django 5.0.4 on 2024-09-24 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_companyinfo_audio_alter_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='policy',
            field=models.FileField(blank=True, null=True, upload_to='company_info/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 15, 34, 42, 143439)),
        ),
    ]
