# Generated by Django 5.0.4 on 2024-09-25 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_client_gender_alter_article_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'Pending'), ('s', 'Succeeded'), ('f', 'Failed'), ('c', 'Canceled')], default='p', help_text='Payment status', max_length=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 1, 4, 32, 528210)),
        ),
    ]
